SELECT 
  PARSE_DATE('%d/%m/%Y', NULLIF(DT_GERACAO, '')) AS dt_geracao, 
  PARSE_TIME('%H:%M:%S', NULLIF(HH_GERACAO, '')) AS hh_geracao, 
  CAST(NULLIF(ANO_ELEICAO, '') AS INT64) AS ano_eleicao, 
  CAST(NULLIF(CD_TIPO_ELEICAO, '') AS INT64) AS cd_tipo_eleicao, 
  NULLIF(NM_TIPO_ELEICAO, '') AS tipo_eleicao, 
  CAST(NULLIF(NR_TURNO, '') AS INT64) AS nr_turno, 
  CAST(NULLIF(CD_ELEICAO, '') AS INT64) AS cd_eleicao, 
  NULLIF(DS_ELEICAO, '') AS eleicao,
  PARSE_DATE('%d/%m/%Y', NULLIF(DT_ELEICAO, '')) AS dt_eleicao, 
  NULLIF(TP_ABRANGENCIA, '') AS tipo_abrangencia, 
  NULLIF(SG_UF, '') AS sg_uf,
  NULLIF(SG_UE, '') AS sg_ue,
  NULLIF(NM_UE, '') AS ue,
  CAST(NULLIF(CD_CARGO, '') AS INT64) AS cd_cargo, 
  NULLIF(DS_CARGO, '') AS ds_cargo,
  CAST(NULLIF(SQ_CANDIDATO, '') AS INT64) AS sq_candidato, 
  CAST(REPLACE(NULLIF(NR_CANDIDATO, ''), '.0', '') AS INT64) AS num_urna_candidato, 
  NULLIF(NM_CANDIDATO, '') AS nome_candidato,
  NULLIF(NM_URNA_CANDIDATO, '') AS nome_urna_candidato, 
  NULLIF(NM_SOCIAL_CANDIDATO, '') AS nome_social_candidato,
  REPLACE(REPLACE(NULLIF(NR_CPF_CANDIDATO, ''), ' ', ''), '-', '') AS cpf_candidato_str,
  NULLIF(NM_EMAIL, '') AS email_candidato,
  CAST(NULLIF(CD_SITUACAO_CANDIDATURA, '') AS INT64) AS cd_situacao_candidatura, 
  NULLIF(DS_SITUACAO_CANDIDATURA, '') AS situacao_candidatura,
  CAST(NULLIF(CD_DETALHE_SITUACAO_CAND, '') AS INT64) AS cd_detalhe_situacao_cand, 
  NULLIF(DS_DETALHE_SITUACAO_CAND, '') AS detalhe_situacao_cand,
  NULLIF(TP_AGREMIACAO, '') AS tipo_agremiacao,
  CAST(NULLIF(NR_PARTIDO, '') AS INT64) AS num_partido,
  NULLIF(SG_PARTIDO, '') AS sigla_partido_original,
  NULLIF(NM_PARTIDO, '') AS nome_partido,
  CAST(NULLIF(SQ_COLIGACAO, '') AS INT64) AS sq_coligacao,
  NULLIF(NM_COLIGACAO, '') AS nome_coligacao,
  NULLIF(DS_COMPOSICAO_COLIGACAO, '') AS composicao_coligacao,
  CAST(NULLIF(CD_NACIONALIDADE, '') AS INT64) AS cd_nacionalidade,
  NULLIF(DS_NACIONALIDADE, '') AS nacionalidade,
  NULLIF(SG_UF_NASCIMENTO, '') AS sigla_uf_nascimento,
  CAST(NULLIF(CD_MUNICIPIO_NASCIMENTO, '') AS INT64) AS cd_municipio_nascimento,
  NULLIF(NM_MUNICIPIO_NASCIMENTO, '') AS municipio_nascimento,
  SAFE.PARSE_DATE('%d/%m/%Y', NULLIF(DT_NASCIMENTO, '')) AS dt_nascimento,
  CAST(REPLACE(NULLIF(NR_IDADE_DATA_POSSE, ''), '.0', '') AS INT64) AS idade_data_posse,
  NULLIF(NR_TITULO_ELEITORAL_CANDIDATO, '') AS titulo_eleitoral_candidato_str,
  CAST(NULLIF(CD_GENERO, '') AS INT64) AS cd_genero,
  NULLIF(DS_GENERO, '') AS genero,
  CAST(NULLIF(CD_GRAU_INSTRUCAO, '') AS INT64) AS cd_grau_instrucao,
  NULLIF(DS_GRAU_INSTRUCAO, '') AS grau_instrucao,
  CAST(NULLIF(CD_ESTADO_CIVIL, '') AS INT64) AS cd_estado_civil,
  NULLIF(DS_ESTADO_CIVIL, '') AS estado_civil,
  CAST(NULLIF(CD_COR_RACA, '') AS INT64) AS cd_cor_raca,
  NULLIF(DS_COR_RACA, '') AS cor_raca,
  CAST(NULLIF(CD_OCUPACAO, '') AS INT64) AS cd_ocupacao,
  NULLIF(DS_OCUPACAO, '') AS ocupacao,
  CAST(NULLIF(VR_DESPESA_MAX_CAMPANHA, '') AS FLOAT64) AS valor_despesa_max_campanha,
  CAST(REPLACE(NULLIF(CD_SIT_TOT_TURNO, ''), '.0', '') AS INT64) AS cd_situacao_tot_turno,
  NULLIF(DS_SIT_TOT_TURNO, '') AS situacao_tot_turno,
  NULLIF(ST_REELEICAO, '') AS situacao_reeleicao,
  NULLIF(ST_DECLARAR_BENS, '') AS situacao_declarar_bens,
  CAST(REPLACE(NULLIF(NR_PROTOCOLO_CANDIDATURA, ''), '.0', '') AS INT64) AS num_propocolo_candidatura,
  NULLIF(NR_PROCESSO, '') AS num_processo_str,
  CAST(REPLACE(NULLIF(CD_SITUACAO_CANDIDATO_PLEITO, ''), '.0', '') AS INT64) AS cd_situacao_candidato_pleito,
  NULLIF(DS_SITUACAO_CANDIDATO_PLEITO, '') AS situacao_candidato_pleito,
  CAST(REPLACE(NULLIF(CD_SITUACAO_CANDIDATO_URNA, ''), '.0', '') AS INT64) AS cd_situacao_candidato_urna,
  NULLIF(DS_SITUACAO_CANDIDATO_URNA, '') AS situacao_candidato_urna,
  NULLIF(ST_CANDIDATO_INSERIDO_URNA, '') AS candidato_inserido_urna,
  NULLIF(IDADE_DATA_ELEICAO, '') AS idade_data_eleicao,
  NULLIF(SG_LEGENDA, '') AS sigla_legenda,
  part_ano,
  part_uf
FROM `gabinete-compartilhado.tratado_tse.consulta_candidatos` 