# Hard-coded to build the table 'afastamentos_civis'
bq --project_id=gabinete-compartilhado load --source_format=CSV --skip_leading_rows=1 --hive_partitioning_mode=AUTO --hive_partitioning_source_uri_prefix=gs://brutos-publicos/executivo/federal/servidores/partitioned/ executivo_federal_servidores.afastamentos_civis gs://brutos-publicos/executivo/federal/servidores/partitioned/*_Afastamentos_cleaned.csv ano:INTEGER,mes:INTEGER,id_servidor:INTEGER,cpf:STRING,nome:STRING,data_inicio_afastamento:STRING,data_fim_afastamento:STRING

# Hard-coded to build the table 'cadastro_civis'
bq --project_id=gabinete-compartilhado load --source_format=CSV --skip_leading_rows=1 --hive_partitioning_mode=AUTO --hive_partitioning_source_uri_prefix=gs://brutos-publicos/executivo/federal/servidores/partitioned/ executivo_federal_servidores.cadastro_civis gs://brutos-publicos/executivo/federal/servidores/partitioned/*_Cadastro_cleaned.csv mes:INTEGER,ano:INTEGER,id_servidor:INTEGER,nome:STRING,cpf:STRING,matricula:STRING,desc_cargo:STRING,classe_cargo:STRING,ref_cargo:INTEGER,padrao_cargo:STRING,nivel_cargo:INTEGER,sigla_funcao:STRING,nivel_funcao:STRING,funcao:STRING,cod_atividade:STRING,atividade:STRING,opcao_parcial:STRING,cod_uorg_lotacao:STRING,uorg_lotacao:STRING,cod_org_lotacao:STRING,org_lotacao:STRING,cod_orgsup_lotacao:STRING,orgsup_lotacao:STRING,cod_uorg_exercicio:STRING,uorg_exercicio:STRING,cod_org_exercicio:STRING,org_exercicio:STRING,cod_orgsup_exercicio:STRING,orgsup_exercicio:STRING,tipo_vinculo:INTEGER,situacao_vinculo:STRING,inicio_afastamento:STRING,termino_afastamento:STRING,regime_juridico:STRING,jornada_de_trabalho:STRING,ingresso_cargo_funcao:STRING,nomeacao_cargo_funcao:STRING,ingresso_orgao:STRING,doc_ingresso_servico_publico:STRING,data_dipl_ingresso_servico_publico:STRING,dipl_ingresso_cargo_funcao:STRING,dipl_ingresso_orgao:STRING,dipl_ingresso_servico_publico:STRING,uf_exercicio:STRING

# Hard-coded to build the table 'servidores_federais_civis_cadastro' in dataset 'views_publicos'
bq --project_id=gabinete-compartilhado load --source_format=CSV --skip_leading_rows=1 --hive_partitioning_mode=AUTO --hive_partitioning_source_uri_prefix=gs://brutos-publicos/executivo/federal/servidores/partitioned/ views_publicos.servidores_federais_civis_cadastro gs://brutos-publicos/executivo/federal/servidores/partitioned/*_Cadastro_cleaned.csv mes:INTEGER,ano:INTEGER,id_servidor:INTEGER,nome:STRING,cpf:STRING,matricula:STRING,desc_cargo:STRING,classe_cargo:STRING,ref_cargo:INTEGER,padrao_cargo:STRING,nivel_cargo:INTEGER,sigla_funcao:STRING,nivel_funcao:STRING,funcao:STRING,cod_atividade:STRING,atividade:STRING,opcao_parcial:STRING,cod_uorg_lotacao:STRING,uorg_lotacao:STRING,cod_org_lotacao:STRING,org_lotacao:STRING,cod_orgsup_lotacao:STRING,orgsup_lotacao:STRING,cod_uorg_exercicio:STRING,uorg_exercicio:STRING,cod_org_exercicio:STRING,org_exercicio:STRING,cod_orgsup_exercicio:STRING,orgsup_exercicio:STRING,tipo_vinculo:INTEGER,situacao_vinculo:STRING,inicio_afastamento:STRING,termino_afastamento:STRING,regime_juridico:STRING,jornada_de_trabalho:STRING,ingresso_cargo_funcao:STRING,nomeacao_cargo_funcao:STRING,ingresso_orgao:STRING,doc_ingresso_servico_publico:STRING,data_dipl_ingresso_servico_publico:STRING,dipl_ingresso_cargo_funcao:STRING,dipl_ingresso_orgao:STRING,dipl_ingresso_servico_publico:STRING,uf_exercicio:STRING

# Hard-coded to build the table 'dou_bruto' in dataset 'views_publicos'
bq --project_id=gabinete-compartilhado load --source_format=NEWLINE_DELIMITED_JSON --hive_partitioning_mode=CUSTOM --hive_partitioning_source_uri_prefix=gs://brutos-publicos/executivo/federal/dou-partitioned/{part_data_pub:DATE}/{part_secao:STRING} views_publicos.dou_bruto gs://brutos-publicos/executivo/federal/dou-partitioned/*.json api_url:STRING,capture_date:TIMESTAMP,url:STRING,url_certificado:STRING,key:STRING,value:STRING
